### ISSUE TITLE
Running environment of SHE_Server

### ISSUE THREAD

**Issue by Luke7799** [DAL3X/somewhat-homomorphic-encryption-system#1]
May I ask whether SHE_Server is required to operate under linux or windows?

**Comment by DAL3X** [comment]
Hi Luke,
the SHE_Server component is executed by the ARM processor on the Xilinx Zynq UltraScale+ MPSoC ZCU102 board. The board comes with two default operation modes: **Standalone** (no operation system), or a preloaded version of **Petalinux**. Since the SHE_Server component used the implementation from  [Roy et al.](https://github.com/KULeuven-COSIC/HEAT/tree/master) as a base, it uses the **standalone** operation mode. 

The client components use Linux sockets to communicate with the server, hence Linux is required for executing them.

**Comment by Luke7799** [comment]
Hello, DAL3X. Sorry to interrupt again. I tried to build your SHE_Server project on Vitis.2020.1. At first, there was an error indicating that some parameters could not be found. I overwrote the _design folder according to the prompt in readme to solve the problem. But then comes a new error about lwip:
make[1]: *** [Makefile:35: liblwip4.a] Error 1

On the Console screen:
aarch64-none-elf-ar: ./*.o: Invalid argument
make[1]: *** [Makefile:35: liblwip4.a] Error 1
make: *** [Makefile:30: psu_cortexa53_0/libsrc/lwip211_v1_0/src/make.libs] Error 2
Failed to build  the bsp sources for domain - ntw_bsp_domain
Failed to generate the platform.
Reason: Failed to generate the zynqmp_pmufw application.

This seems to be caused by the liblwip4.a static library creation failure. But I don't know if this is the "lwip missing" problem mentioned later in the readme, I failed to deal with it the way you wrote to solve the "lwip missing" problem at the end. Have you ever encountered this problem？

**Comment by Luke7799** [comment]
Hello, DAL3X. Sorry to interrupt again. I tried to build your SHE_Server project on Vitis.2020.1. At first, there was an error indicating that some parameters could not be found. I overwrote the _design folder according to the prompt in readme to solve the problem. But then comes a new error about lwip:
make[1]: *** [Makefile:35: liblwip4.a] Error 1

On the Console screen:
aarch64-none-elf-ar: ./*.o: Invalid argument
make[1]: *** [Makefile:35: liblwip4.a] Error 1
make: *** [Makefile:30: psu_cortexa53_0/libsrc/lwip211_v1_0/src/make.libs] Error 2
Failed to build the bsp sources for domain - ntw_bsp_domain
Failed to generate the platform.
Reason: Failed to generate the zynqmp_pmufw application.

This appears to be caused by a failure to create the liblwip4.a static library. But I don't know if this has anything to do with the "lwip missing" issue mentioned later in the readme, which I tackled in the same way without success. Have you ever encountered this problem?

**Comment by DAL3X** [comment]
Hello again Luke,
unfortunately I can't help you with this specific problem. 
The [base project](https://github.com/KULeuven-COSIC/HEAT/tree/master/ZCU102) used Vivado 2018.3. I used the same software to avoid any backwards compatibility problems. Migrating the project to Vitis 2020.1 might cause problems. I would advise to try building the project with this version of Vivado and see if the same problem arises.

**Comment by Luke7799** [comment]
Thank you very much. The content you uploaded is very helpful for me to learn FHE. Another question I have is, did you make any changes to Roy's implementation in Vivado's hardware design? Because I only see here that you uploaded the exported.hdf(.xsa) file.

**Comment by DAL3X** [comment]
I did not change any hardware design parts. 
I also want to stress that this project does not use FHE, but SHE instead. The hardware design should be able to support four multiplications before the noise becomes too high.
