### ISSUE TITLE
About ZCU102

### ISSUE THREAD

**Issue by w1072769898** [DAL3X/somewhat-homomorphic-encryption-system#2]
Hi, DAL3X.
I don't have a ZCU102 board, but I do have one other board that is consistent with the ZCU102 chip (xczu9eg). Can this project be transplanted into my zynq board?

**Comment by DAL3X** [comment]
Hello w107,
unfortunately my experience with FPGA boards is too little to definitively answer your question. I suspect that the software part (which is the only code I changed) should run on compatible chips without, or only with minor modifications.
You should probably check the hardware design compatibility first by getting the [Roy et al.](https://github.com/KULeuven-COSIC/HEAT/tree/master) implementation to run and then build my modifications on top as described in the corresponding readme file.

**Comment by w1072769898** [comment]
风染白
***@***.***


I also want to ask whether the Vitis software you use is the Linux version or the Windows version?
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DAL3X/somewhat-homomorphic-encryption-system"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月29日(星期三) 晚上8:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DAL3X/somewhat-homomorphic-encryption-system] About ZCU102 (Issue #2)





 
Hello w107,
 unfortunately my experience with FPGA boards is too little to definitively answer your question. I suspect that the software part (which is the only code I changed) should run on compatible chips without, or only with minor modifications.
 You should probably check the hardware design compatibility first by getting the Roy et al. implementation to run and then build my modifications on top.

**Comment by DAL3X** [comment]
Vivado 2018.3 on Linux was used to build and test all SHE server code.
